name: Generate Stats Telemetry SVG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Stats SVG
        run: node scripts/generateStats.js
